### ISSUE TITLE
remove (buffer-file-name) as default 

### ISSUE THREAD

**Issue by milkypostman** [magnars/angular-snippets.el#1]
I am having some issues with desktop mode where when I use the angular snippets, it tries to load the snippets from my working directory of the file i'm using.

i think what is happening is that the buffer is visiting a file so it's using `(buffer-file-name)` for the path.

thus, on line 138 i think you should just use the `load-file-name` and cut the `(buffer-file-name)`, or at least swap them.

https://github.com/magnars/angular-snippets.el/blob/master/angular-snippets.el#L138

**Comment by magnars** [comment]
I didn't realize there was a case where both load-file-name and buffer-file-name was set. Thanks, I've swapped them now.

**Comment by milkypostman** [comment]
Is this in here for the case where you eval the buffer?

**Comment by magnars** [comment]
Yep. But somewhere along the way the snippets have stopped working all together. I'm looking into it.
