### ISSUE TITLE
Unify string quote style

### ISSUE THREAD

**Issue by iquiw** [magnars/angular-snippets.el#5]
In the current snippets, both double quote and single quote are used as JavaScript string quote.
I changed double quote to single quote. ([1])
https://github.com/iquiw/angular-snippets.el/tree/single-quote

If you like the change, I will send a pull request.
Otherwise, ignore this :)

[1] https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Strings#Strings

**Comment by magnars** [comment]
I use double quotes. ;-) I guess the best solution would involve a setting to switch between the two.

**Comment by iquiw** [comment]
> I use double quotes. ;-)

I see.

> I guess the best solution would involve a setting to switch between the two.

I will check how it can be done by YASnippet some time.

Thanks.
